{% set name = "charm" %}
{% set version = "7.0.0" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UIUC-PPL/charm/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 83fc2be261f9a586b6595a3589c385a8160006fa872fbfa26659e1363feeb72b

build:
  number: {{ build }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - sysroot_linux-64 2.17  # [linux64]

test:
  commands:
    - echo true

about:
  home: https://charm.cs.illinois.edu
  license: Custom
  license_file: LICENSE
  summary: The Charm++ parallel programming system.
  doc_url: https://github.com/UIUC-PPL/charm/
  dev_url: https://charm.readthedocs.io

extra:
  recipe-maintainers:
    - matthiasdiener
